language: android
android:
  components:
    - build-tools-26.0.2
    - android-27
    - android-21
    - add-on
    - extra
    - platform-tools
    - tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-armeabi-v7a-android-21

before_install:
  - yes | sdkmanager "platforms;android-27"

deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
    - janos.velenyak@gmail.com
    on_success: always
    on_failure: always